jht3820/oslits

oslits/src/main/webapp/WEB-INF/jsp/oslits/cmm/cmm4000/cmm4000/cmm4000.jsp

- 로그인 화면 한글입력 불가로 변경

---

oslits/src/main/webapp/WEB-INF/jsp/oslits/adm/adm7000/adm7000/adm7000.jsp

- 조직 트리에 root만 있을 떄 조회 클릭 시  
트리에 빈 값이 추가되는 현상 수정

조직 트리 조회부분 수정

---

oslits/src/main/resources/egovframework/sqlmap/oslits/prj/prj3000/prj3000/prj3000_SQL_Oracle.xml

개발문서 양식 관리 쿼리수정

---

oslits/src/main/resources/egovframework/sqlmap/oslits/prj/prj2000/prj2000/prj2000_SQL_Oracle.xml

역할그룹 조회 쿼리 수정

---

oslits/src/main/webapp/WEB-INF/jsp/oslits/prj/prj2000/prj2000/prj2001.jsp

역할그룹 추가 시 설명 필수입력에서 제외

---

oslits/src/main/webapp/WEB-INF/jsp/oslits/prj/prj2000/prj2000/prj2001.jsp

역할그룹 설명 필수값 표시 제거, 우선순위를 정렬순서로 명칭변경

역할그룹 설명 필수값 표시 제거, 우선순위를 정렬순서로 명칭변경

---

oslits/src/main/webapp/WEB-INF/jsp/oslits/req/req4000/req4000/req4000.jsp

요구사항 분류 조회 버튼 클릭시 ROOT 아래 아무것도 없는경우 트리 메뉴가 추가로 붙는 현상 수정

요구사항 분류 조회 수정

---

oslits/src/main/resources/egovframework/message/message-common_ko.properties

조직목록 엑셀 다운로드시 헤더 명칭 수정

---

oslits/src/main/webapp/WEB-INF/jsp/oslits/chk/chk1000/chk1100/chk1100.jsp

결재 승인 반려 저장시 에러처리 수정

---

oslits/src/main/webapp/js/common/comOslits.js

프린트 브라우저 프린트로 수정

---

oslits/src/main/webapp/WEB-INF/jsp/oslits/chk/chk1000/chk1100/chk1100.jsp

결재 선택 데이터 없을경우 경고창 알림

---

oslits/src/main/java/kr/opensoftlab/oslits/com/fms/web/FileMngController.java

압축파일 다운로드인코딩 수정

---

oslits/src/main/webapp/WEB-INF/jsp/oslits/prj/prj2000/prj2000/prj2000.jsp

시스템 권한 체크박스 사이즈 변경

---

oslits/src/main/webapp/WEB-INF/jsp/oslits/stm/stm1000/stm1200/stm1200.jsp
oslits/src/main/webapp/WEB-INF/jsp/oslits/stm/stm2000/stm2000/stm2000.jsp
oslits/src/main/webapp/WEB-INF/jsp/oslits/stm/stm2000/stm2200/stm2200.jsp

전체 API 토큰 목록, SVN저장소 등록관리, SVN저장소 전체 현황 엑셀파일명 변경

엑셀파일명 변경 : 전체 API 토큰 목록, SVN저장소 등록관리, SVN저장소 전체 현황

---

oslits/src/main/webapp/WEB-INF/jsp/oslits/stm/stm3000/stm3000/stm3000.jsp
oslits/src/main/webapp/WEB-INF/jsp/oslits/stm/stm3000/stm3200/stm3200.jsp

JENKINS 등록관리, 전체현황 그리드 엑셀 다운로드 파일명 변경

JENKINS 등록관리, 전체현황 그리드 엑셀 다운로드 파일명 변경

---

oslits/src/main/webapp/WEB-INF/jsp/oslops/adm/adm1000/adm1000/adm1000.jsp

메뉴 및 권한관리에서 권한 가로체크 기능 추가, 버그 수정
편의성 위해 체크박스 가로체크 추가
메뉴 및 권한관리의 권한관리탭 가로체크 추가

메뉴 및 권한관리 - 권한관리 가로 전체체크 추가

---

oslits/src/main/webapp/WEB-INF/jsp/oslops/prj/prj1000/prj1100/prj1100.jsp
oslits/src/main/webapp/WEB-INF/jsp/oslops/prj/prj1000/prj1100/prj1101.jsp
oslits/src/main/webapp/WEB-INF/jsp/oslops/prj/prj1000/prj1100/prj1102.jsp
oslits/src/main/webapp/WEB-INF/jsp/oslops/prj/prj1000/prj1100/prj1103.jsp
oslits/src/main/webapp/WEB-INF/jsp/oslops/prj/prj1000/prj1100/prj1104.jsp
oslits/src/main/webapp/WEB-INF/jsp/oslops/prj/prj1000/prj1100/prj1105.jsp
oslits/src/main/webapp/WEB-INF/jsp/oslops/req/req4000/req4500/req4500.jsp

프로세스 설정 : 프로세스 복사 추가, 작업흐름 허용역할 설정 추가
요구사항 이력조회 : 요구사항 이력조회시 담당자 변경 이력 빈칸으로 나오는 부분 수정
프로세스 설정 : 프로세스 복사 추가, 작업흐름 허용역할 설정 추가
요구사항 이력조회 : 요구사항 이력조회시 담당자 변경 이력 빈칸으로 나오는 부분 수정
prj1100.jsp, prj1101.jsp, prj1102.jsp, prj1103.jsp, prj1104.jsp, prj1105.jsp
req4500.jsp

프로세스 설정, 요구사항 이력조회 수정

---

oslits/src/main/webapp/WEB-INF/jsp/oslops/prj/prj2000/prj2000/prj2000.jsp
oslits/src/main/webapp/WEB-INF/jsp/oslops/prj/prj2000/prj2000/prj2001.jsp
oslits/src/main/webapp/WEB-INF/jsp/oslops/prj/prj2000/prj2100/prj2100.jsp

- 업무역할 추가 팝업의 이중 스크롤 수정
- 미사용 권한이 업무역할 사용자 배정에 표시되지 않도록 수정
- 업무역할 추가 팝업의 이중 스크롤 수정
- 미사용 권한이 업무역할 사용자 배정에 표시되지 않도록 수정
prj2000.jsp, prj2001.jsp, prj2100.jsp

업무역할 관리 수정

---

oslits/src/main/webapp/WEB-INF/jsp/oslops/dsh/dsh1000/dsh1000/dsh1000.jsp

운영대시보드 담당 요구사항 결재목록, 공지사항 그리드가 폴딩시 동시에 접히는 현상 수정
담당 요구사항 결재 목록 또는 공지사항 목록에서 폴딩버튼 클릭 시 두 그리드 모두 동시에 접히는 현상 수정
dsh1000.jsp

운영대시보드 그리드 폴딩 문제 수정

---

oslits/src/main/webapp/WEB-INF/jsp/oslops/dsh/dsh1000/dsh1000/dsh1001.jsp

운영대시보드 신호등 클릭시 관련된 요구사항 목록 표시되는 팝업 추가
운영대시보드 신호등 클릭시 관련된 요구사항 목록 표시되는 팝업 추가
dsh1001.jsp

운영대시보드 신호등 클릭시 관련된 요구사항 목록 표시되는 팝업 추가

---

oslits/src/main/webapp/WEB-INF/jsp/oslops/dsh/dsh3000/dsh3000/dsh3000.jsp

통합대시보드 차트 표시기준 수정
통합대시보드 차트 표시기준 수정
dsh3000.jsp

통합대시보드 차트 표시기준 수정

---

oslits/src/main/webapp/WEB-INF/jsp/oslops/dsh/dsh2000/dsh2000/dsh2000.jsp
oslits/src/main/webapp/WEB-INF/jsp/oslops/dsh/dsh2000/dsh2000/dsh2001.jsp
oslits/src/main/webapp/WEB-INF/jsp/oslops/dsh/dsh3000/dsh3000/dsh3001.jsp

통합대시보드 신호등 클릭시 관련 요구사항 목록 표시되는 팝업 추가
통합대시보드 신호등 클릭시 관련 요구사항 목록 표시되는 팝업 추가
통합대시보드 신호등 클릭시 관련 요구사항 목록 표시되는 팝업 추가

통합대시보드 신호등 클릭시 관련 요구사항 목록 표시되는 팝업 추가

---

oslits/src/main/webapp/WEB-INF/jsp/oslops/prj/prj1000/prj1000/prj1000.jsp

프로젝트 수정, 삭제시 상단 프로젝트 선택부분에 수정, 삭제된 내역이 일부 반영되지 않던 문제 수정
프로젝트 수정, 삭제시 상단 프로젝트 선택부분에 수정, 삭제된 내역이 일부 반영되지 않던 문제 수정

프로젝트 수정, 삭제시 상단 프로젝트 선택부분 문제 수정

---

oslits/src/main/webapp/WEB-INF/jsp/oslops/top/header.jsp

상단 프로젝트선택부분에서 프로젝트 검색할 수 있도록 변경
상단 프로젝트 선택부분에서 프로젝트를 검색하여 선택할 수 있도록 변경
- 프로젝트가 많을 경우 사용자가 프로젝트 선택을 쉽게할 수 있도록 검색 추가
header.jsp

상단 프로젝트선택부분에서 프로젝트 검색할 수 있도록 변경

---

oslits/src/main/webapp/WEB-INF/jsp/oslops/prj/prj3000/prj3000/prj3000.jsp

확정 개발문서 양식 삭제시 삭제한 개발문서 양식이 하단 개발문서 양식 업로드 부분에 남아있는 문제 수정
산출물 양식 관리에서 업로드된 개발문서 양식을 확정 개발문서 양식으로 이동 후 확정 개발문서 양식을 삭제하면, 업로드된 개발문서 양식 목록에 삭제한 개발문서 양식이 나오는 문제 수정
prj3000.jsp

확정 개발문서 양식 삭제시 삭제한 개발문서 양식이 하단 개발문서 양식 업로드 부분에 남아있는 문제 수정

---

oslits/src/main/webapp/WEB-INF/jsp/oslops/prj/prj1000/prj1000/prj1002.jsp
oslits/src/main/webapp/WEB-INF/jsp/oslops/prj/prj1000/prj1000/prj1003.jsp

최초 프로젝트 그룹 및 프로젝트 생성 팝업 유효성 조건 수정
순번 숫자체크 유효성 수정
프로젝트 생성시 약어 유효성 조건 변경 - 영문에서 영문+숫자로
prj1002,jsp , prj1003.jep

최초 프로젝트 그룹 및 프로젝트 생성 팝업 유효성 조건 수정

---

oslits/src/main/webapp/WEB-INF/jsp/oslops/prj/prj3000/prj3100/prj3100.jsp

확정 개발문서 삭제시 개발문서 업로드 영역에 삭제한 확정 개발문서가 다시 보이는 문제 수정
산출물 관리에서 업로드한 개발문서를 확정 개발문서로 이동하고, 확정개발문서를 삭제하면
삭제한 확정 개발문서가 업로드된 개발문서 목록에 표시되는 문제 수정
prj3100.jsp

확정 개발문서 삭제시 개발문서 업로드 영역에 삭제한 확정 개발문서가 다시 보이는 문제 수정

---

oslits/src/main/webapp/WEB-INF/jsp/oslops/stm/stm1000/stm1100/stm1100.jsp

API 토큰관리 화면 오류 수정
API 토큰관리 화면에서 발생하는  success error: TypeError: Cannot read property 'length' of undefined 오류 수정
stm1000.jsp

API 토큰관리 화면 오류 수정

---

oslits/src/main/webapp/WEB-INF/jsp/oslops/stm/stm1000/stm1000/stm1000.jsp
oslits/src/main/webapp/WEB-INF/jsp/oslops/stm/stm1000/stm1000/stm1001.jsp
oslits/src/main/webapp/WEB-INF/jsp/oslops/stm/stm1000/stm1200/stm1200.jsp

API 등록/수정 팝업의 header 수정
API 등록/수정 팝업의 header 수정, API 목록 그리드 프린트 수정

API 등록/수정 팝업의 header 수정

---

oslits/src/main/webapp/WEB-INF/jsp/oslops/stm/stm2000/stm2100/stm2100.jsp
oslits/src/main/webapp/WEB-INF/jsp/oslops/stm/stm2000/stm2100/stm2102.jsp

svn 저장소 배정관리 오류 수정
svn 배정관리 메뉴 접근시 success error: TypeError: Cannot read property 'length' of undefined 오류 수정

svn 저장소 배정관리 오류 수정

---

oslits/src/main/webapp/WEB-INF/jsp/oslops/stm/stm2000/stm2000/stm2000.jsp
oslits/src/main/webapp/WEB-INF/jsp/oslops/stm/stm2000/stm2000/stm2001.jsp
oslits/src/main/webapp/WEB-INF/jsp/oslops/stm/stm2000/stm2200/stm2200.jsp

SVN 저장소 그리드 및 저장소 등록/수정 팝업 수정
SVN 저장소 그리드 및 저장소 등록/수정 팝업 수정

SVN 저장소 그리드 및 저장소 등록/수정 팝업 수정

---

oslits/src/main/webapp/WEB-INF/jsp/oslops/req/req4000/req4200/req4200.jsp

요구사항 분류 배정관리 수정
- 분류에 배정/미배정된 요구사항 그리드에 표시되는 항목 변경
- 요구사항 그리드 쪽지 수정
- 요구사항을 분류에 배정/미배정 소스 수정

요구사항 분류 배정관리 수정

---

oslits/src/main/webapp/WEB-INF/jsp/oslops/req/req4000/req4000/req4000.jsp

요구사항 분류 추가/삭제 수정
- 요구사항 분류 기존3뎁스까지 추가에서 무한뎁스 추가로 변경
- 요구사항 분류 삭제시 분류에 요구사항이 배정되어 있지 않을 경우 하위 분류까지 모두 삭제하도록 변경
req4000.jsp

요구사항 분류 추가/삭제 수정

---

oslits/src/main/webapp/WEB-INF/jsp/oslops/chk/chk1000/chk1000/chk1000.jsp
oslits/src/main/webapp/WEB-INF/jsp/oslops/chk/chk1000/chk1100/chk1100.jsp

결재 승인/반려시 다음 작업흐름에 따라 분기처리
- 다음 작업흐름이 최종완료일 경우 작업흐름 id null,
아닐경우 다음 작업흐름 id 넘김

결재 승인/반려시 다음 작업흐름에 따라 분기처리

---

oslits/src/main/webapp/WEB-INF/jsp/oslops/adm/adm2000/adm2000/adm2001.jsp
oslits/src/main/webapp/WEB-INF/jsp/oslops/adm/adm2000/adm2000/adm2002.jsp
oslits/src/main/webapp/WEB-INF/jsp/oslops/adm/adm2000/adm2000/adm2003.jsp
oslits/src/main/webapp/WEB-INF/jsp/oslops/req/req4000/req4100/req4103.jsp

사용자/요구사항 요청자 이메일입력시 공백제거 처리
사용자 등록/수정시 이메일 입력시 공백제거
요구사항엑셀 업로드시 사용자 이메일 공백제거

사용자/요구사항 요청자 이메일입력시 공백제거 처리

---

oslits/src/main/webapp/WEB-INF/jsp/oslops/req/req1000/req1000/req1001.jsp
oslits/src/main/webapp/WEB-INF/jsp/oslops/req/req1000/req1000/req1002.jsp

사용자 요구사항 등록 팝업 수정
- 팝업 사이즈 변경, CSS 수정, 이메일 공백제거
- 요청자 직급/직책 추가

사용자 요구사항 등록 팝업 수정

---

README.md

영문 README 수정
오라클에서 큐브리드로 DB 전환에 따라 큐브리드 설정 설명 추가

영문 README 수정
